// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/home-layouts/CardStack.tsx": () => import("../components/mockups/home-layouts/CardStack.tsx"),
  "./components/mockups/home-layouts/FormFirst.tsx": () => import("../components/mockups/home-layouts/FormFirst.tsx"),
  "./components/mockups/home-layouts/SplitScreen.tsx": () => import("../components/mockups/home-layouts/SplitScreen.tsx")
};
